[tool.poetry]
name = "ml"
version = "0.1.0"
description = ""
authors = ["Jaseem Abid <me@jabid.in>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.0.0"
ipdb = "^0.13.13"
numpy = "^1.26.4"
pytest = "^8.0.1"
matplotlib = "^3.8.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
